<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rona_nvblox</name>
  <version>0.0.1</version>
  <description>This package contains files for rona navigation</description>
  <maintainer email="sachin.kumar@iml.fraunhofer.de">Sachin Kumar</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>isaac_ros_visual_slam</depend>
  <depend>nvblox_examples_bringup</depend>
  <depend>nvblox_msgs</depend>
  <depend>nvblox_nav2</depend>
  <depend>nvblox_ros_common</depend>
  <depend>nvblox_ros_python_utils</depend>
  <depend>nvblox_ros</depend>
  <depend>nvblox_rviz_plugin</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
